services:
  - type: web
    name: cropguard-ai-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CROPGUARD_MODEL_URL
        value: https://raw.githubusercontent.com/Chandangowdakt/CropGuard-AI/main/backend/models/chrysanthemum_leaf_model.pth
      - key: CROPGUARD_LEAF_MODEL_URL
        value: https://raw.githubusercontent.com/Chandangowdakt/CropGuard-AI/main/backend/models/chrysanthemum_leaf_model.pth
